[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
thiserror = "1.0.40"
clap = { version = "4.3.2", features = ["derive"] }
niffler = "2.5.0"
noodles = { version = "0.40.0", features = ["fasta"] }
env_logger = "0.10.0"
log = "0.4.19"
itertools = "0.10.5"